#!/usr/bin/env bash

count=0  # 初始化计数器
last_n=0 # 初始化保存前一个 n 值的变量

# 循环直到出错
while true; do
    last_n=$n               # 保存当前 n 值到 last_n
    n=$(( RANDOM % 100 ))   # 生成一个新的随机数

    if [[ $n -eq 42 ]]; then
        echo "Error occurred."
        echo "Cause by sth" >&2
        echo "脚本总共运行了 $count 次，出错前 n 的值是 $last_n"
        exit 1
    fi

    count=$((count + 1)) # 增加计数
done
